import = ["~/.config/alacritty/kanagawa-wave.toml"]

[font]
size = 13.5

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"
