import = ["~/.config/alacritty/an-old-hope.toml"]

[font]
size = 14

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"
style = "Retina"
